import AppCore
import Daylily
import Foundation
import Logging
import PostgresNIO

public struct PostgresCommerceRepository: Sendable {
    public let client: PostgresClient
    private let timeout: Duration
    private let logger = Logger(label: "commerce.database")

    public init(client: PostgresClient, timeout: Duration = .seconds(4)) {
        self.client = client
        self.timeout = timeout
    }

    // Cancellation closes a leased connection, including a query waiting on a broken
    // network. Pool waiters are cancellation-aware. No detached timeout work survives.
    private func perform<Value: Sendable>(
        timeout: Duration? = nil,
        _ operation: @escaping @Sendable (PostgresConnection) async throws -> Value
    ) async throws -> Value {
        try await withThrowingTaskGroup(of: Value.self) { group in
            group.addTask {
                try await client.withConnection { connection in
                    try await withTaskCancellationHandler {
                        try await operation(connection)
                    } onCancel: {
                        connection.close().whenFailure { _ in }
                    }
                }
            }
            group.addTask {
                try await Task.sleep(for: timeout ?? self.timeout)
                throw DatabaseUnavailable()
            }
            defer { group.cancelAll() }
            return try await group.next()!
        }
    }

    private func execute(_ query: PostgresQuery, on connection: PostgresConnection) async throws {
        for try await _ in try await connection.query(query, logger: logger) {}
    }

    // Migration takes an advisory transaction lock so simultaneous replicas do not race
    // PostgreSQL catalog creation. This is an initial example schema, not a migration engine.
    public func migrate() async throws {
        try await perform(timeout: .seconds(15)) { connection in
            try await execute("BEGIN", on: connection)
            do {
                try await execute("SELECT pg_advisory_xact_lock(730026001)", on: connection)
                try await execute("""
                    CREATE TABLE IF NOT EXISTS commerce_products (
                        id BIGINT PRIMARY KEY, name TEXT NOT NULL, category TEXT NOT NULL,
                        price_cents BIGINT NOT NULL CHECK (price_cents >= 0), in_stock BOOLEAN NOT NULL
                    )
                    """, on: connection)
                try await execute("""
                    CREATE TABLE IF NOT EXISTS commerce_order_keys (
                        key TEXT PRIMARY KEY CHECK (octet_length(key) BETWEEN 1 AND 128)
                    )
                    """, on: connection)
                try await execute("""
                    CREATE TABLE IF NOT EXISTS commerce_orders (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1001) PRIMARY KEY,
                        idempotency_key TEXT UNIQUE, request JSONB NOT NULL, payload JSONB NOT NULL,
                        created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
                    )
                    """, on: connection)
                try await execute("""
                    INSERT INTO commerce_products (id, name, category, price_cents, in_stock) VALUES
                    (1, 'Jasmine Green Tea', 'tea', 1299, true),
                    (2, 'Oolong Sampler', 'tea', 1899, true),
                    (3, 'Ceramic Tasting Cup', 'tools', 2500, true),
                    (4, 'Seasonal Gift Box', 'gifts', 4200, false)
                    ON CONFLICT (id) DO NOTHING
                    """, on: connection)
                try await execute("COMMIT", on: connection)
            } catch {
                try? await execute("ROLLBACK", on: connection)
                throw error
            }
        }
    }

    public func checkReady() async throws {
        try await perform { connection in try await execute("SELECT 1", on: connection) }
    }

    public func products(category: String?) async throws -> [Product] {
        try await perform { connection in
            let rows = try await connection.query("""
                SELECT id, name, category, price_cents, in_stock FROM commerce_products
                WHERE (\(category)::text IS NULL OR category = \(category)) ORDER BY id
                """, logger: logger)
            var result: [Product] = []
            for try await (id, name, category, price, stock) in rows.decode((Int, String, String, Int, Bool).self) {
                result.append(Product(id: id, name: name, category: category, priceCents: price, inStock: stock))
            }
            return result
        }
    }

    public func product(id: Int) async throws -> Product? {
        try await perform { connection in try await loadProduct(id: id, on: connection) }
    }

    private func loadProduct(id: Int, on connection: PostgresConnection) async throws -> Product? {
        let rows = try await connection.query("""
            SELECT id, name, category, price_cents, in_stock FROM commerce_products
            WHERE id = \(id) FOR SHARE
            """, logger: logger)
        var result: Product?
        for try await (id, name, category, price, stock) in rows.decode((Int, String, String, Int, Bool).self) {
            result = Product(id: id, name: name, category: category, priceCents: price, inStock: stock)
        }
        return result
    }

    public func order(id: Int) async throws -> Order? {
        try await perform { connection in
            let rows = try await connection.query(
                "SELECT id, payload::text FROM commerce_orders WHERE id = \(id)", logger: logger)
            var result: Order?
            for try await (id, payload) in rows.decode((Int, String).self) {
                result = try JSONDecoder().decode(StoredOrder.self, from: Data(payload.utf8)).order(id: id)
            }
            return result
        }
    }

    public static func validate(_ input: CreateOrderRequest, idempotencyKey: String?) throws {
        guard !input.customerEmail.isEmpty, input.customerEmail.utf8.count <= 320 else {
            throw Abort(.badRequest, reason: "Customer email must contain 1 to 320 bytes")
        }
        guard (1...100).contains(input.items.count) else {
            throw Abort(.badRequest, reason: "Order must contain 1 to 100 items")
        }
        guard input.items.allSatisfy({ $0.productID > 0 && (1...10_000).contains($0.quantity) }) else {
            throw Abort(.badRequest, reason: "Product IDs must be positive and quantities between 1 and 10000")
        }
        if let key = idempotencyKey {
            guard (1...128).contains(key.utf8.count), key.utf8.allSatisfy({ (33...126).contains($0) }) else {
                throw Abort(.badRequest, reason: "Idempotency-Key must contain 1 to 128 visible ASCII bytes")
            }
        }
    }

    public func createOrder(_ input: CreateOrderRequest, idempotencyKey: String?) async throws -> Order {
        try Self.validate(input, idempotencyKey: idempotencyKey)
        return try await perform { connection in
            try await execute("BEGIN", on: connection)
            do {
                // Serialize the whole keyed operation, including the initial lookup.
                // A unique full-text key avoids application hash collisions; a failed
                // transaction rolls back a newly reserved key along with its order.
                if let idempotencyKey {
                    try await execute("""
                        INSERT INTO commerce_order_keys (key) VALUES (\(idempotencyKey))
                        ON CONFLICT (key) DO NOTHING
                        """, on: connection)
                    try await execute("""
                        SELECT key FROM commerce_order_keys WHERE key = \(idempotencyKey) FOR UPDATE
                        """, on: connection)
                    let existing = try await connection.query("""
                        SELECT id, request::text, payload::text FROM commerce_orders
                        WHERE idempotency_key = \(idempotencyKey)
                        """, logger: logger)
                    var replay: Order?
                    for try await (id, originalRequest, storedPayload) in existing.decode((Int, String, String).self) {
                        let original = try JSONDecoder().decode(CreateOrderRequest.self, from: Data(originalRequest.utf8))
                        guard original == input else {
                            throw Abort(Status(409, reasonPhrase: "Conflict"), reason: "Idempotency-Key already used for a different order")
                        }
                        replay = try JSONDecoder().decode(StoredOrder.self, from: Data(storedPayload.utf8)).order(id: id)
                    }
                    if let replay {
                        try await execute("COMMIT", on: connection)
                        return replay
                    }
                }
                var lines: [OrderLine] = []
                var total = 0
                for item in input.items {
                    guard let product = try await loadProduct(id: item.productID, on: connection) else {
                        throw Abort(.notFound, reason: "Product not found")
                    }
                    guard product.inStock else { throw Abort(.badRequest, reason: "Product is out of stock") }
                    let (lineTotal, overflow) = product.priceCents.multipliedReportingOverflow(by: item.quantity)
                    let (newTotal, sumOverflow) = total.addingReportingOverflow(lineTotal)
                    guard !overflow, !sumOverflow else { throw Abort(.badRequest, reason: "Order total exceeds supported range") }
                    total = newTotal
                    lines.append(OrderLine(productID: product.id, name: product.name, quantity: item.quantity,
                                           unitPriceCents: product.priceCents, lineTotalCents: lineTotal))
                }
                let payload = StoredOrder(customerEmail: input.customerEmail, status: "accepted", items: lines, totalCents: total)
                let payloadJSON = String(decoding: try JSONEncoder().encode(payload), as: UTF8.self)
                let requestJSON = String(decoding: try JSONEncoder().encode(input), as: UTF8.self)
                let rows = try await connection.query("""
                    INSERT INTO commerce_orders (idempotency_key, request, payload)
                    VALUES (\(idempotencyKey), \(requestJSON)::jsonb, \(payloadJSON)::jsonb)
                    ON CONFLICT (idempotency_key) DO UPDATE SET idempotency_key = EXCLUDED.idempotency_key
                    RETURNING id, request::text, payload::text
                    """, logger: logger)
                var order: Order?
                for try await (id, originalRequest, storedPayload) in rows.decode((Int, String, String).self) {
                    let original = try JSONDecoder().decode(CreateOrderRequest.self, from: Data(originalRequest.utf8))
                    guard original == input else {
                        throw Abort(Status(409, reasonPhrase: "Conflict"), reason: "Idempotency-Key already used for a different order")
                    }
                    order = try JSONDecoder().decode(StoredOrder.self, from: Data(storedPayload.utf8)).order(id: id)
                }
                guard let order else { throw DatabaseUnavailable() }
                try await execute("COMMIT", on: connection)
                return order
            } catch {
                try? await execute("ROLLBACK", on: connection)
                throw error
            }
        }
    }
}

private struct StoredOrder: Codable, Sendable {
    let customerEmail: String
    let status: String
    let items: [OrderLine]
    let totalCents: Int
    func order(id: Int) -> Order {
        Order(id: id, customerEmail: customerEmail, status: status, items: items, totalCents: totalCents)
    }
}

public struct DatabaseUnavailable: Error, Sendable {}
